function Depth_MAT = interD_mat(LFD, P_r, P_1, P_2, U_r, U_1, U_2, H)
    global Params;

    P_1(P_r == 1) = 0;    P_2(P_r == 0) = 0;
    U_1(U_r == 1) = 0;    U_2(U_r == 0) = 0;
    
    Depth_MAT = ((1.0 - P_r) .* ...
                ((1.0 - U_r) .* (im2double(LFD((P_1) * (Params.Height * Params.Width) + U_1 * (Params.Height) + H + 1))) + ...
                      ((U_r) .* (im2double(LFD((P_1) * (Params.Height * Params.Width) + U_2 * (Params.Height) + H + 1)))))) + ...
                      ((P_r) .* ...
                ((1.0 - U_r) .* (im2double(LFD((P_2) * (Params.Height * Params.Width) + U_1 * (Params.Height) + H + 1))) + ...
                      ((U_r) .* (im2double(LFD((P_2) * (Params.Height * Params.Width) + U_2 * (Params.Height) + H + 1))))));
end